insert into public.questions
(id, difficulty, category, prompt, answers, correct_answer, active)
values
(1, 1, 'Conhecimentos Gerais', 'Qual animal é conhecido por miar?', '["Gato", "Cavalo", "Galinha", "Coelho"]'::jsonb, 'Gato', true),
(2, 1, 'Geografia', 'Qual é a capital do Brasil?', '["Brasília", "São Paulo", "Rio de Janeiro", "Salvador"]'::jsonb, 'Brasília', true),
(3, 1, 'Ciência', 'Quantos dias normalmente tem uma semana?', '["7", "5", "6", "8"]'::jsonb, '7', true),
(4, 1, 'Cultura Pop', 'Qual super-herói é conhecido como Homem-Aranha?', '["Peter Parker", "Bruce Wayne", "Clark Kent", "Tony Stark"]'::jsonb, 'Peter Parker', true),
(5, 1, 'Gastronomia', 'Qual destes é um tipo de massa italiana?', '["Espaguete", "Sushi", "Taco", "Cuscuz"]'::jsonb, 'Espaguete', true),
(6, 1, 'Música', 'Qual instrumento geralmente tem seis cordas?', '["Violão", "Flauta", "Trompete", "Pandeiro"]'::jsonb, 'Violão', true),
(7, 1, 'Esportes', 'No futebol, qual parte do corpo o goleiro pode usar para segurar a bola dentro da área?', '["Mãos", "Cotovelos apenas", "Cabeça apenas", "Pés apenas"]'::jsonb, 'Mãos', true),
(8, 1, 'História', 'Em qual país ficam as pirâmides de Gizé?', '["Egito", "México", "Índia", "Grécia"]'::jsonb, 'Egito', true),
(9, 1, 'Geografia', 'Qual destes é um oceano?', '["Atlântico", "Saara", "Andes", "Nilo"]'::jsonb, 'Atlântico', true),
(10, 1, 'Ciência', 'A água congela, ao nível do mar, aproximadamente a quantos graus Celsius?', '["0 °C", "10 °C", "50 °C", "100 °C"]'::jsonb, '0 °C', true),
(11, 1, 'Cinema', 'Qual personagem vive em uma casa de abacaxi no fundo do mar?', '["Bob Esponja", "Shrek", "Garfield", "Scooby-Doo"]'::jsonb, 'Bob Esponja', true),
(12, 1, 'Conhecimentos Gerais', 'Quantos meses há em um ano?', '["12", "10", "11", "13"]'::jsonb, '12', true),
(13, 1, 'Gastronomia', 'Qual bebida é produzida pela fermentação de uvas?', '["Vinho", "Café", "Chá", "Refrigerante"]'::jsonb, 'Vinho', true),
(14, 1, 'Geografia', 'Qual destes países fica na América do Sul?', '["Argentina", "Japão", "Noruega", "Egito"]'::jsonb, 'Argentina', true),
(15, 1, 'Ciência', 'Qual planeta é conhecido como Planeta Vermelho?', '["Marte", "Vênus", "Júpiter", "Netuno"]'::jsonb, 'Marte', true),
(16, 1, 'Música', 'Quem canta normalmente em um karaokê?', '["O participante", "O garçom obrigatoriamente", "Somente uma banda", "Apenas o DJ"]'::jsonb, 'O participante', true),
(17, 1, 'Esportes', 'Quantos jogadores cada time tem em campo no futebol, no início da partida?', '["11", "9", "10", "12"]'::jsonb, '11', true),
(18, 1, 'Conhecimentos Gerais', 'Qual destes objetos serve para indicar as horas?', '["Relógio", "Garfo", "Travesseiro", "Escova"]'::jsonb, 'Relógio', true),
(19, 1, 'Geografia', 'Qual é a maior cidade do estado de São Paulo em população?', '["São Paulo", "Jundiaí", "Santos", "Campinas"]'::jsonb, 'São Paulo', true),
(20, 1, 'Cultura Pop', 'Qual personagem é um encanador da Nintendo?', '["Mario", "Sonic", "Kratos", "Pikachu"]'::jsonb, 'Mario', true),
(21, 2, 'Geografia', 'Qual é a capital da Argentina?', '["Buenos Aires", "Rosário", "Córdoba", "Mendoza"]'::jsonb, 'Buenos Aires', true),
(22, 2, 'Ciência', 'Qual gás é essencial para a respiração humana?', '["Oxigênio", "Hélio", "Neônio", "Hidrogênio"]'::jsonb, 'Oxigênio', true),
(23, 2, 'História', 'Quem foi o primeiro imperador do Brasil?', '["Dom Pedro I", "Dom Pedro II", "Getúlio Vargas", "Deodoro da Fonseca"]'::jsonb, 'Dom Pedro I', true),
(24, 2, 'Música', 'Qual banda gravou ''Bohemian Rhapsody''?', '["Queen", "U2", "Oasis", "Nirvana"]'::jsonb, 'Queen', true),
(25, 2, 'Gastronomia', 'Qual destilado é a base clássica da caipirinha?', '["Cachaça", "Gin", "Rum", "Whisky"]'::jsonb, 'Cachaça', true),
(26, 2, 'Esportes', 'Quantos pontos vale uma cesta de lance livre no basquete?', '["1", "2", "3", "4"]'::jsonb, '1', true),
(27, 2, 'Cinema', 'Qual ogro verde é protagonista de uma famosa franquia de animação?', '["Shrek", "Hulk", "Grinch", "Yoda"]'::jsonb, 'Shrek', true),
(28, 2, 'Geografia', 'Qual país tem Lisboa como capital?', '["Portugal", "Espanha", "Itália", "Bélgica"]'::jsonb, 'Portugal', true),
(29, 2, 'Ciência', 'Qual órgão bombeia o sangue pelo corpo?', '["Coração", "Pulmão", "Fígado", "Rim"]'::jsonb, 'Coração', true),
(30, 2, 'Conhecimentos Gerais', 'Quantos lados tem um hexágono?', '["6", "5", "7", "8"]'::jsonb, '6', true),
(31, 2, 'História', 'A chegada dos portugueses ao Brasil ocorreu em qual século?', '["Século XVI", "Século XIV", "Século XV", "Século XVII"]'::jsonb, 'Século XVI', true),
(32, 2, 'Cultura Pop', 'Qual é o nome do ratinho mascote da Disney?', '["Mickey Mouse", "Jerry", "Stuart Little", "Remy"]'::jsonb, 'Mickey Mouse', true),
(33, 2, 'Geografia', 'Qual rio é famoso por atravessar o Egito?', '["Nilo", "Danúbio", "Mississippi", "Tâmisa"]'::jsonb, 'Nilo', true),
(34, 2, 'Música', 'Qual destes instrumentos tem teclas pretas e brancas?', '["Piano", "Violino", "Saxofone", "Bateria"]'::jsonb, 'Piano', true),
(35, 2, 'Gastronomia', 'Guacamole é preparado principalmente com qual ingrediente?', '["Abacate", "Batata", "Tomate", "Pepino"]'::jsonb, 'Abacate', true),
(36, 2, 'Esportes', 'Em qual esporte se usa uma raquete e uma peteca?', '["Badminton", "Rugby", "Handebol", "Beisebol"]'::jsonb, 'Badminton', true),
(37, 2, 'Ciência', 'Qual é o satélite natural da Terra?', '["Lua", "Sol", "Marte", "Vênus"]'::jsonb, 'Lua', true),
(38, 2, 'Conhecimentos Gerais', 'Qual idioma é falado majoritariamente no Brasil?', '["Português", "Espanhol", "Francês", "Italiano"]'::jsonb, 'Português', true),
(39, 3, 'Geografia', 'Qual é a capital do Canadá?', '["Ottawa", "Toronto", "Vancouver", "Montreal"]'::jsonb, 'Ottawa', true),
(40, 3, 'Ciência', 'Qual elemento químico tem símbolo Fe?', '["Ferro", "Flúor", "Fósforo", "Frâncio"]'::jsonb, 'Ferro', true),
(41, 3, 'História', 'Qual navegante é tradicionalmente associado à chegada portuguesa ao Brasil em 1500?', '["Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães", "Américo Vespúcio"]'::jsonb, 'Pedro Álvares Cabral', true),
(42, 3, 'Literatura', 'Quem escreveu ''Dom Casmurro''?', '["Machado de Assis", "José de Alencar", "Lima Barreto", "Graciliano Ramos"]'::jsonb, 'Machado de Assis', true),
(43, 3, 'Música', 'Qual grupo britânico tinha John Lennon e Paul McCartney?', '["The Beatles", "The Rolling Stones", "Pink Floyd", "The Who"]'::jsonb, 'The Beatles', true),
(44, 3, 'Gastronomia', 'Margarita clássica leva tequila, limão e qual licor?', '["Licor de laranja", "Licor de café", "Amaretto", "Vermute tinto"]'::jsonb, 'Licor de laranja', true),
(45, 3, 'Esportes', 'Qual país venceu a Copa do Mundo masculina de 2002?', '["Brasil", "Alemanha", "França", "Argentina"]'::jsonb, 'Brasil', true),
(46, 3, 'Cinema', 'Quem é o arqueólogo aventureiro interpretado por Harrison Ford em uma famosa franquia?', '["Indiana Jones", "Rocky Balboa", "John Rambo", "Ethan Hunt"]'::jsonb, 'Indiana Jones', true),
(47, 3, 'Geografia', 'Qual é o maior oceano da Terra?', '["Pacífico", "Atlântico", "Índico", "Ártico"]'::jsonb, 'Pacífico', true),
(48, 3, 'Ciência', 'Qual é a raiz quadrada de 144?', '["12", "10", "11", "14"]'::jsonb, '12', true),
(49, 3, 'História', 'Qual civilização construiu Machu Picchu?', '["Inca", "Maia", "Asteca", "Romana"]'::jsonb, 'Inca', true),
(50, 3, 'Cultura Pop', 'Qual criatura amarela é mascote da franquia Pokémon?', '["Pikachu", "Charmander", "Meowth", "Psyduck"]'::jsonb, 'Pikachu', true),
(51, 3, 'Geografia', 'Qual país tem Tóquio como capital?', '["Japão", "China", "Coreia do Sul", "Tailândia"]'::jsonb, 'Japão', true),
(52, 3, 'Música', 'Qual cantor ficou conhecido como ''Rei do Pop''?', '["Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"]'::jsonb, 'Michael Jackson', true),
(53, 3, 'Ciência', 'Qual vitamina é produzida pelo corpo com ajuda da exposição ao sol?', '["Vitamina D", "Vitamina C", "Vitamina B12", "Vitamina K"]'::jsonb, 'Vitamina D', true),
(54, 3, 'Conhecimentos Gerais', 'Quantos minutos há em duas horas e meia?', '["150", "120", "135", "180"]'::jsonb, '150', true),
(55, 4, 'Geografia', 'Qual destes países não faz fronteira com o Brasil?', '["Chile", "Bolívia", "Peru", "Colômbia"]'::jsonb, 'Chile', true),
(56, 4, 'Ciência', 'Qual é o maior órgão do corpo humano?', '["Pele", "Fígado", "Pulmão", "Coração"]'::jsonb, 'Pele', true),
(57, 4, 'História', 'A Revolução Francesa começou em qual ano?', '["1789", "1776", "1815", "1848"]'::jsonb, '1789', true),
(58, 4, 'Literatura', 'Quem escreveu ''O Pequeno Príncipe''?', '["Antoine de Saint-Exupéry", "Victor Hugo", "Jules Verne", "Albert Camus"]'::jsonb, 'Antoine de Saint-Exupéry', true),
(59, 4, 'Música', 'Qual banda lançou o álbum ''The Dark Side of the Moon''?', '["Pink Floyd", "Queen", "Led Zeppelin", "The Doors"]'::jsonb, 'Pink Floyd', true),
(60, 4, 'Gastronomia', 'Qual ingrediente dá a cor característica ao risoto alla milanese?', '["Açafrão", "Páprica", "Cúrcuma", "Tomate"]'::jsonb, 'Açafrão', true),
(61, 4, 'Esportes', 'Em qual cidade foram realizados os Jogos Olímpicos de 2016?', '["Rio de Janeiro", "São Paulo", "Londres", "Tóquio"]'::jsonb, 'Rio de Janeiro', true),
(62, 4, 'Cinema', 'Qual diretor comandou ''Titanic'' e ''Avatar''?', '["James Cameron", "Steven Spielberg", "Ridley Scott", "Christopher Nolan"]'::jsonb, 'James Cameron', true),
(63, 4, 'Geografia', 'Qual é a capital da Austrália?', '["Canberra", "Sydney", "Melbourne", "Perth"]'::jsonb, 'Canberra', true),
(64, 4, 'Ciência', 'Qual partícula possui carga elétrica negativa?', '["Elétron", "Próton", "Nêutron", "Fóton"]'::jsonb, 'Elétron', true),
(65, 4, 'História', 'Quem proclamou a República no Brasil em 1889?', '["Deodoro da Fonseca", "Floriano Peixoto", "Getúlio Vargas", "Juscelino Kubitschek"]'::jsonb, 'Deodoro da Fonseca', true),
(66, 4, 'Cultura Pop', 'Qual série apresenta as casas Stark, Lannister e Targaryen?', '["Game of Thrones", "Vikings", "The Witcher", "Lost"]'::jsonb, 'Game of Thrones', true),
(67, 4, 'Música', 'Qual instrumento é associado a Louis Armstrong?', '["Trompete", "Piano", "Violoncelo", "Flauta"]'::jsonb, 'Trompete', true),
(68, 4, 'Conhecimentos Gerais', 'Se um produto custa R$ 80 e recebe 25% de desconto, qual é o preço final?', '["R$ 60", "R$ 55", "R$ 65", "R$ 70"]'::jsonb, 'R$ 60', true),
(69, 5, 'Geografia', 'Qual é a capital da Turquia?', '["Ancara", "Istambul", "Esmirna", "Bursa"]'::jsonb, 'Ancara', true),
(70, 5, 'Ciência', 'Qual cientista formulou as três leis do movimento clássicas?', '["Isaac Newton", "Charles Darwin", "Louis Pasteur", "Niels Bohr"]'::jsonb, 'Isaac Newton', true),
(71, 5, 'História', 'Qual tratado encerrou oficialmente a Primeira Guerra Mundial entre Alemanha e Aliados?', '["Tratado de Versalhes", "Tratado de Tordesilhas", "Tratado de Utrecht", "Tratado de Paris de 1763"]'::jsonb, 'Tratado de Versalhes', true),
(72, 5, 'Literatura', 'Quem escreveu ''1984''?', '["George Orwell", "Aldous Huxley", "Ray Bradbury", "Franz Kafka"]'::jsonb, 'George Orwell', true),
(73, 5, 'Música', 'Qual compositor ficou famoso por obras como a Quinta Sinfonia e ''Für Elise''?', '["Beethoven", "Mozart", "Bach", "Chopin"]'::jsonb, 'Beethoven', true),
(74, 5, 'Gastronomia', 'Em um Negroni clássico, gin é combinado com Campari e qual outro ingrediente?', '["Vermute tinto", "Vermute seco", "Cointreau", "Licor de café"]'::jsonb, 'Vermute tinto', true),
(75, 5, 'Esportes', 'Quantos sets um tenista masculino precisa vencer em uma partida de melhor de cinco sets?', '["3", "2", "4", "5"]'::jsonb, '3', true),
(76, 5, 'Cinema', 'Qual filme de 1994 apresenta os personagens Vincent Vega e Jules Winnfield?', '["Pulp Fiction", "Seven", "Clube da Luta", "Os Bons Companheiros"]'::jsonb, 'Pulp Fiction', true),
(77, 5, 'Geografia', 'Qual cadeia de montanhas separa, em grande parte, a Europa da Ásia na Rússia?', '["Montes Urais", "Alpes", "Andes", "Cárpatos"]'::jsonb, 'Montes Urais', true),
(78, 5, 'Ciência', 'Qual é a fórmula química da água oxigenada?', '["H₂O₂", "H₂O", "CO₂", "O₃"]'::jsonb, 'H₂O₂', true),
(79, 5, 'História', 'Quem foi o líder sul-africano que se tornou presidente em 1994 após décadas de apartheid?', '["Nelson Mandela", "Desmond Tutu", "F. W. de Klerk", "Thabo Mbeki"]'::jsonb, 'Nelson Mandela', true),
(80, 5, 'Conhecimentos Gerais', 'Qual número romano representa 50?', '["L", "C", "D", "X"]'::jsonb, 'L', true),
(81, 6, 'Geografia', 'Qual é a capital da Nova Zelândia?', '["Wellington", "Auckland", "Christchurch", "Hamilton"]'::jsonb, 'Wellington', true),
(82, 6, 'Ciência', 'Qual escala mede a dureza dos minerais de 1 a 10?', '["Escala de Mohs", "Escala Richter", "Escala Kelvin", "Escala Beaufort"]'::jsonb, 'Escala de Mohs', true),
(83, 6, 'História', 'Qual imperador francês foi derrotado definitivamente na Batalha de Waterloo?', '["Napoleão Bonaparte", "Luís XIV", "Carlos Magno", "Napoleão III"]'::jsonb, 'Napoleão Bonaparte', true),
(84, 6, 'Literatura', 'Qual autor criou o detetive Sherlock Holmes?', '["Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "G. K. Chesterton"]'::jsonb, 'Arthur Conan Doyle', true),
(85, 6, 'Música', 'Qual compositor escreveu ''As Quatro Estações''?', '["Antonio Vivaldi", "Giacomo Puccini", "Johannes Brahms", "Claude Debussy"]'::jsonb, 'Antonio Vivaldi', true),
(86, 6, 'Gastronomia', 'Qual destilado é tradicionalmente usado no coquetel Daiquiri?', '["Rum branco", "Vodka", "Gin", "Bourbon"]'::jsonb, 'Rum branco', true),
(87, 6, 'Esportes', 'Em qual país surgiu o judô?', '["Japão", "China", "Coreia do Sul", "Tailândia"]'::jsonb, 'Japão', true),
(88, 6, 'Cinema', 'Qual atriz interpretou Hermione Granger nos filmes de Harry Potter?', '["Emma Watson", "Keira Knightley", "Natalie Portman", "Emma Stone"]'::jsonb, 'Emma Watson', true),
(89, 6, 'Geografia', 'Qual estreito separa a Espanha do Marrocos?', '["Estreito de Gibraltar", "Estreito de Bering", "Bósforo", "Dardanelos"]'::jsonb, 'Estreito de Gibraltar', true),
(90, 6, 'Ciência', 'Qual é o nome do processo pelo qual plantas convertem luz em energia química?', '["Fotossíntese", "Fermentação", "Osmose", "Respiração anaeróbica"]'::jsonb, 'Fotossíntese', true),
(91, 7, 'História', 'Qual cidade romana foi soterrada pela erupção do Vesúvio em 79 d.C.?', '["Pompeia", "Cartago", "Esparta", "Ravena"]'::jsonb, 'Pompeia', true),
(92, 7, 'Geografia', 'Qual país africano tem Adis Abeba como capital?', '["Etiópia", "Quênia", "Eritreia", "Sudão"]'::jsonb, 'Etiópia', true),
(93, 7, 'Ciência', 'Qual camada da atmosfera concentra a maior parte do ozônio que filtra radiação ultravioleta?', '["Estratosfera", "Troposfera", "Mesosfera", "Termosfera"]'::jsonb, 'Estratosfera', true),
(94, 7, 'Literatura', 'Quem escreveu ''Cem Anos de Solidão''?', '["Gabriel García Márquez", "Mario Vargas Llosa", "Jorge Luis Borges", "Pablo Neruda"]'::jsonb, 'Gabriel García Márquez', true),
(95, 7, 'Música', 'Qual banda irlandesa lançou o álbum ''The Joshua Tree''?', '["U2", "The Cranberries", "Oasis", "R.E.M."]'::jsonb, 'U2', true),
(96, 7, 'Gastronomia', 'Qual queijo italiano é tradicionalmente usado no tiramisù?', '["Mascarpone", "Gorgonzola", "Pecorino", "Provolone"]'::jsonb, 'Mascarpone', true),
(97, 7, 'Esportes', 'Qual é a distância oficial de uma maratona?', '["42,195 km", "40 km", "41,2 km", "45 km"]'::jsonb, '42,195 km', true),
(98, 7, 'Cinema', 'Qual diretor criou a trilogia ''O Senhor dos Anéis'' lançada entre 2001 e 2003?', '["Peter Jackson", "George Lucas", "Sam Raimi", "Guillermo del Toro"]'::jsonb, 'Peter Jackson', true),
(99, 7, 'História', 'Qual povo construiu a cidade de Petra, na atual Jordânia?', '["Nabateus", "Fenícios", "Hititas", "Sumérios"]'::jsonb, 'Nabateus', true),
(100, 7, 'Ciência', 'Qual unidade do SI mede resistência elétrica?', '["Ohm", "Watt", "Tesla", "Pascal"]'::jsonb, 'Ohm', true),
(101, 8, 'Geografia', 'Qual é a capital do Cazaquistão?', '["Astana", "Almaty", "Tashkent", "Bishkek"]'::jsonb, 'Astana', true),
(102, 8, 'Ciência', 'Qual é o número atômico do carbono?', '["6", "4", "8", "12"]'::jsonb, '6', true),
(103, 8, 'História', 'Qual dinastia chinesa construiu grande parte da Cidade Proibida em Pequim?', '["Ming", "Qing", "Han", "Tang"]'::jsonb, 'Ming', true),
(104, 8, 'Literatura', 'Em ''Os Miseráveis'', qual é o nome do ex-presidiário protagonista?', '["Jean Valjean", "Javert", "Marius Pontmercy", "Thenardier"]'::jsonb, 'Jean Valjean', true),
(105, 8, 'Música', 'Qual compositor escreveu a ópera ''A Flauta Mágica''?', '["Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Giacomo Puccini"]'::jsonb, 'Wolfgang Amadeus Mozart', true),
(106, 8, 'Gastronomia', 'Qual técnica culinária francesa consiste em cozinhar lentamente um alimento submerso em gordura?', '["Confit", "Brasear", "Flambar", "Escalfar"]'::jsonb, 'Confit', true),
(107, 8, 'Esportes', 'Qual país venceu a primeira Copa do Mundo de futebol masculino, em 1930?', '["Uruguai", "Argentina", "Brasil", "Itália"]'::jsonb, 'Uruguai', true),
(108, 8, 'Cinema', 'Qual filme de Stanley Kubrick é baseado em um romance de Anthony Burgess?', '["Laranja Mecânica", "O Iluminado", "Barry Lyndon", "Nascido para Matar"]'::jsonb, 'Laranja Mecânica', true),
(109, 9, 'Geografia', 'Qual é a capital da Eslovênia?', '["Liubliana", "Bratislava", "Zagreb", "Sarajevo"]'::jsonb, 'Liubliana', true),
(110, 9, 'Ciência', 'Qual físico propôs o princípio da incerteza na mecânica quântica?', '["Werner Heisenberg", "Erwin Schrödinger", "Max Planck", "Paul Dirac"]'::jsonb, 'Werner Heisenberg', true),
(111, 9, 'História', 'Qual batalha de 1066 consolidou a conquista normanda da Inglaterra?', '["Batalha de Hastings", "Batalha de Agincourt", "Batalha de Bosworth", "Batalha de Stamford Bridge"]'::jsonb, 'Batalha de Hastings', true),
(112, 9, 'Literatura', 'Quem escreveu ''O Nome da Rosa''?', '["Umberto Eco", "Italo Calvino", "Primo Levi", "Alberto Moravia"]'::jsonb, 'Umberto Eco', true),
(113, 9, 'Música', 'Qual músico de jazz lançou o álbum ''Kind of Blue''?', '["Miles Davis", "John Coltrane", "Duke Ellington", "Thelonious Monk"]'::jsonb, 'Miles Davis', true),
(114, 9, 'Gastronomia', 'Qual vinho fortificado é ingrediente tradicional do coquetel Bamboo?', '["Xerez", "Porto", "Madeira", "Marsala"]'::jsonb, 'Xerez', true),
(115, 9, 'Esportes', 'No snooker, quantos pontos vale a bola preta?', '["7", "5", "6", "8"]'::jsonb, '7', true),
(116, 9, 'Cinema', 'Qual cineasta japonês dirigiu ''Os Sete Samurais''?', '["Akira Kurosawa", "Yasujirō Ozu", "Kenji Mizoguchi", "Hayao Miyazaki"]'::jsonb, 'Akira Kurosawa', true),
(117, 10, 'Geografia', 'Qual é a capital do Butão?', '["Thimphu", "Paro", "Kathmandu", "Daca"]'::jsonb, 'Thimphu', true),
(118, 10, 'Ciência', 'Qual organela celular é responsável principalmente pela produção de ATP na respiração aeróbica?', '["Mitocôndria", "Lisossomo", "Ribossomo", "Complexo de Golgi"]'::jsonb, 'Mitocôndria', true),
(119, 10, 'História', 'Qual tratado de 1648 é associado ao fim da Guerra dos Trinta Anos?', '["Paz de Vestfália", "Tratado de Viena", "Tratado de Utrecht", "Paz de Augsburgo"]'::jsonb, 'Paz de Vestfália', true),
(120, 10, 'Literatura', 'Qual autor escreveu ''O Som e a Fúria''?', '["William Faulkner", "Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck"]'::jsonb, 'William Faulkner', true),
(121, 10, 'Música', 'Qual compositor escreveu o balé ''A Sagração da Primavera''?', '["Igor Stravinsky", "Sergei Prokofiev", "Pyotr Tchaikovsky", "Dmitri Shostakovich"]'::jsonb, 'Igor Stravinsky', true),
(122, 10, 'Gastronomia', 'Qual molho clássico francês é uma emulsão quente de gemas e manteiga clarificada?', '["Hollandaise", "Béchamel", "Velouté", "Espagnole"]'::jsonb, 'Hollandaise', true),
(123, 10, 'Esportes', 'Em qual cidade nasceu o movimento olímpico moderno com os primeiros Jogos de 1896?', '["Atenas", "Paris", "Londres", "Roma"]'::jsonb, 'Atenas', true),
(124, 10, 'Cinema', 'Qual filme de Federico Fellini venceu o Oscar de Melhor Filme Estrangeiro e acompanha o cineasta Guido Anselmi?', '["8½", "La Dolce Vita", "Amarcord", "Noites de Cabíria"]'::jsonb, '8½', true),
(125, 11, 'Geografia', 'Qual país possui a região autônoma de Gagauzia?', '["Moldávia", "Romênia", "Geórgia", "Bulgária"]'::jsonb, 'Moldávia', true),
(126, 11, 'Ciência', 'Qual constante relaciona a energia de um fóton à sua frequência?', '["Constante de Planck", "Constante de Boltzmann", "Constante de Avogadro", "Constante de Faraday"]'::jsonb, 'Constante de Planck', true),
(127, 11, 'História', 'Qual imperador bizantino ordenou a compilação do Corpus Juris Civilis?', '["Justiniano I", "Constantino XI", "Teodósio I", "Basílio II"]'::jsonb, 'Justiniano I', true),
(128, 11, 'Literatura', 'Qual romance de Thomas Mann acompanha Hans Castorp em um sanatório nos Alpes suíços?', '["A Montanha Mágica", "Morte em Veneza", "Doutor Fausto", "Os Buddenbrook"]'::jsonb, 'A Montanha Mágica', true),
(129, 11, 'Música', 'Qual compositor francês escreveu ''Quarteto para o Fim dos Tempos''?', '["Olivier Messiaen", "Maurice Ravel", "Gabriel Fauré", "Erik Satie"]'::jsonb, 'Olivier Messiaen', true),
(130, 11, 'Gastronomia', 'Qual fungo é tradicionalmente usado para produzir queijos azuis como Roquefort?', '["Penicillium roqueforti", "Saccharomyces cerevisiae", "Aspergillus oryzae", "Rhizopus oligosporus"]'::jsonb, 'Penicillium roqueforti', true),
(131, 12, 'Geografia', 'Qual é a capital de Kiribati?', '["Tarawa do Sul", "Funafuti", "Majuro", "Ngerulmud"]'::jsonb, 'Tarawa do Sul', true),
(132, 12, 'Ciência', 'Qual matemático formulou as equações que unificam eletricidade e magnetismo no século XIX?', '["James Clerk Maxwell", "Michael Faraday", "André-Marie Ampère", "Hendrik Lorentz"]'::jsonb, 'James Clerk Maxwell', true),
(133, 12, 'História', 'Qual batalha naval de 1571 marcou uma grande derrota da frota otomana pela Liga Santa?', '["Batalha de Lepanto", "Batalha de Trafalgar", "Batalha de Salamina", "Batalha de Actium"]'::jsonb, 'Batalha de Lepanto', true),
(134, 12, 'Literatura', 'Quem escreveu o romance ''O Homem sem Qualidades''?', '["Robert Musil", "Hermann Hesse", "Stefan Zweig", "Franz Werfel"]'::jsonb, 'Robert Musil', true),
(135, 12, 'Música', 'Qual compositor escreveu a ópera ''Wozzeck''?', '["Alban Berg", "Arnold Schoenberg", "Anton Webern", "Paul Hindemith"]'::jsonb, 'Alban Berg', true),
(136, 12, 'Cinema', 'Qual diretor realizou o filme japonês ''A Mulher da Areia'', de 1964?', '["Hiroshi Teshigahara", "Masaki Kobayashi", "Nagisa Oshima", "Kon Ichikawa"]'::jsonb, 'Hiroshi Teshigahara', true),
(137, 13, 'Geografia', 'Qual é o ponto mais baixo em terra firme exposta na África?', '["Lago Assal", "Depressão de Qattara", "Lago Tanganica", "Danakil"]'::jsonb, 'Lago Assal', true),
(138, 13, 'Ciência', 'Qual teorema relaciona simetrias contínuas a leis de conservação na física?', '["Teorema de Noether", "Teorema de Green", "Teorema de Bayes", "Teorema de Stokes"]'::jsonb, 'Teorema de Noether', true),
(139, 13, 'História', 'Qual casa dinástica governava a Áustria durante a maior parte da Guerra dos Trinta Anos?', '["Habsburgo", "Bourbon", "Hohenzollern", "Wittelsbach"]'::jsonb, 'Habsburgo', true),
(140, 13, 'Literatura', 'Qual escritor austríaco escreveu ''O Homem sem Posteridade'' e ''Auto de Fé''?', '["Elias Canetti", "Robert Musil", "Joseph Roth", "Arthur Schnitzler"]'::jsonb, 'Elias Canetti', true),
(141, 13, 'Música', 'Qual compositor escreveu a obra orquestral ''Atmosphères'', usada em ''2001: Uma Odisseia no Espaço''?', '["György Ligeti", "Béla Bartók", "Krzysztof Penderecki", "Iannis Xenakis"]'::jsonb, 'György Ligeti', true),
(142, 14, 'Geografia', 'Qual microestado europeu tem Vaduz como capital?', '["Liechtenstein", "Andorra", "San Marino", "Mônaco"]'::jsonb, 'Liechtenstein', true),
(143, 14, 'Ciência', 'Qual físico introduziu o conceito de função de onda em uma equação fundamental da mecânica quântica?', '["Erwin Schrödinger", "Wolfgang Pauli", "Max Born", "Enrico Fermi"]'::jsonb, 'Erwin Schrödinger', true),
(144, 14, 'História', 'Qual imperador romano convocou o Concílio de Niceia de 325?', '["Constantino I", "Teodósio I", "Diocleciano", "Juliano"]'::jsonb, 'Constantino I', true),
(145, 14, 'Literatura', 'Qual obra de Italo Calvino é estruturada como uma conversa entre Marco Polo e Kublai Khan?', '["As Cidades Invisíveis", "O Barão nas Árvores", "Se um Viajante numa Noite de Inverno", "O Cavaleiro Inexistente"]'::jsonb, 'As Cidades Invisíveis', true),
(146, 14, 'Música', 'Qual compositor criou a técnica dodecafônica no início do século XX?', '["Arnold Schoenberg", "Anton Webern", "Alban Berg", "Paul Hindemith"]'::jsonb, 'Arnold Schoenberg', true),
(147, 15, 'Ciência', 'Qual número adimensional expressa a razão entre forças inerciais e viscosas em um fluido?', '["Número de Reynolds", "Número de Mach", "Número de Prandtl", "Número de Froude"]'::jsonb, 'Número de Reynolds', true),
(148, 15, 'História', 'Qual tratado de 1713 encerrou grande parte da Guerra da Sucessão Espanhola?', '["Tratado de Utrecht", "Tratado de Rastatt", "Tratado de Aix-la-Chapelle", "Tratado dos Pireneus"]'::jsonb, 'Tratado de Utrecht', true),
(149, 15, 'Literatura', 'Qual escritor polonês é autor do romance ''Ferdydurke''?', '["Witold Gombrowicz", "Bruno Schulz", "Czesław Miłosz", "Stanisław Lem"]'::jsonb, 'Witold Gombrowicz', true),
(150, 15, 'Música', 'Qual compositor escreveu a ópera ''Lulu'', deixada incompleta à sua morte em 1935?', '["Alban Berg", "Anton Webern", "Arnold Schoenberg", "Richard Strauss"]'::jsonb, 'Alban Berg', true)
on conflict (id) do update set
  difficulty = excluded.difficulty,
  category = excluded.category,
  prompt = excluded.prompt,
  answers = excluded.answers,
  correct_answer = excluded.correct_answer,
  active = excluded.active;
